package euler;

import static org.junit.Assert.*;

import org.junit.Test;

public class Problem2Test {

	/**
	 * Even Fibonacci numbers
	 * 
	 * Problem 2
	 * 
	 * Each new term in the Fibonacci sequence is generated by adding the
	 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 * 
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * 
	 * By considering the terms in the Fibonacci sequence whose values do not
	 * exceed four million, find the sum of the even-valued terms.
	 * 
	 * Answer: 4613732
	 * 
	 * @param args
	 */

	@Test
	public void test() {
		int sum = Problem2.sumOfEvenFibonacciNos(4000000);
		assertEquals("sum does not match", 4613732, sum);
	}

}
